// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"od-srv/internal/biz"
	"od-srv/internal/conf"
	"od-srv/internal/data"
	"od-srv/internal/server"
	"od-srv/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	odRepo := data.NewOdRepo(dataData, logger)
	odUseCase := biz.NewOdUseCate(odRepo, logger)
	cateRepo := data.NewCateRepo(dataData, logger)
	cateUseCase := biz.NewCateUseCase(cateRepo, logger)
	scRepo := data.NewScRepo(dataData, logger)
	scUseCase := biz.NewScUseCase(scRepo, logger)
	odSrv := service.NewOdSrv(odUseCase, cateUseCase, scUseCase, confData, logger)
	httpServer := server.NewHTTPServer(confServer, odSrv, logger)
	grpcServer := server.NewGRPCServer(confServer, odSrv, logger)
	app := newApp(logger, confData, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
