server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s
data:
  pdSrvName: pd-srv
  database:
    driver: mysql
    source: root:zxcvbnm@tcp(172.19.0.2:3306)/miuros
  redis:
    addr: 172.19.0.5:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  rabbit:
    addr: "amqp://root:zxcvbnm@172.19.0.4:5672"
  consul:
    addr: 172.19.0.3:8500
