version: '3'
services:
  maria:
    container_name: maria
    image: docker.io/mariadb:latest
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zxcvbnm
  redis: 
    container_name: redis
    image: docker.io/redis:latest
    ports:
      - "6379"
  rabbit:
    container_name: rabbit
    image: docker.io/rabbitmq:management
    ports: 
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=zxcvbnm
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379"
      - "2380"
    command: "etcd -name etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token cluster -initial-cluster 'etcd=http://etcd:2380' -initial-cluster-state new"
