mail:
  addr: 
  passwd: 
  host: smtp.qq.com
  port: 465

consul:
    addr: 172.19.0.3:8500

http:
    addr: 0.0.0.0:10000

maria:
    driver: mysql
    endpoint: root:zxcvbnm@tcp(172.19.0.2:3306)/micro

jaeger:
    addr: 172.17.0.2:6831

oss:
    base: 
    ak: 
    sk: 
    bucket: 
