// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"user-srv/internal/biz"
	"user-srv/internal/conf"
	"user-srv/internal/data"

	"user-srv/internal/server"
	"user-srv/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}


	userRepo := data.NewUserRepo(dataData, logger)
	addressRepo:=data.NewAddressRepo(dataData,logger)
	userUsecase := biz.NewUserUseCase(userRepo, logger)
	addressUseCase:=biz.NewAddressUseCase(addressRepo,logger)

	userService := service.NewUserService(addressUseCase,userUsecase, logger)
	httpService:=server.NewHTTPServer(confServer,userService,logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	app := newApp(logger,confData, httpService, grpcServer)

	return app, func() {
		cleanup()
	}, nil
}
