// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/notify/v1/notify.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUuid   string `protobuf:"bytes,2,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	UserName   string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	ToUserUuid string `protobuf:"bytes,4,opt,name=toUserUuid,proto3" json:"toUserUuid,omitempty"`
	Content    string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Type       string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CreateAt   string `protobuf:"bytes,7,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Status     int64  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	IsDeleted  int64  `protobuf:"varint,9,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
}

func (x *Notice) Reset() {
	*x = Notice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

func (x *Notice) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notice) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *Notice) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Notice) GetToUserUuid() string {
	if x != nil {
		return x.ToUserUuid
	}
	return ""
}

func (x *Notice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notice) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Notice) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Notice) GetIsDeleted() int64 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

type CreateNtReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N *Notice `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *CreateNtReq) Reset() {
	*x = CreateNtReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNtReq) ProtoMessage() {}

func (x *CreateNtReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNtReq.ProtoReflect.Descriptor instead.
func (*CreateNtReq) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNtReq) GetN() *Notice {
	if x != nil {
		return x.N
	}
	return nil
}

type CreateNtReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateNtReply) Reset() {
	*x = CreateNtReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNtReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNtReply) ProtoMessage() {}

func (x *CreateNtReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNtReply.ProtoReflect.Descriptor instead.
func (*CreateNtReply) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{2}
}

type GetNtReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUuid string `protobuf:"bytes,2,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *GetNtReq) Reset() {
	*x = GetNtReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNtReq) ProtoMessage() {}

func (x *GetNtReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNtReq.ProtoReflect.Descriptor instead.
func (*GetNtReq) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{3}
}

func (x *GetNtReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetNtReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetNtReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetNtReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nt *Notice `protobuf:"bytes,1,opt,name=nt,proto3" json:"nt,omitempty"`
}

func (x *GetNtReply) Reset() {
	*x = GetNtReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNtReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNtReply) ProtoMessage() {}

func (x *GetNtReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNtReply.ProtoReflect.Descriptor instead.
func (*GetNtReply) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{4}
}

func (x *GetNtReply) GetNt() *Notice {
	if x != nil {
		return x.Nt
	}
	return nil
}

type ListNtReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit    uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page     uint64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Status   int64  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	UserUuid string `protobuf:"bytes,5,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
}

func (x *ListNtReq) Reset() {
	*x = ListNtReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNtReq) ProtoMessage() {}

func (x *ListNtReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNtReq.ProtoReflect.Descriptor instead.
func (*ListNtReq) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{5}
}

func (x *ListNtReq) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNtReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNtReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListNtReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListNtReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UserUuid string `protobuf:"bytes,3,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateStatusReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type UpdateStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateStatusReply) Reset() {
	*x = UpdateStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReply) ProtoMessage() {}

func (x *UpdateStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReply.ProtoReflect.Descriptor instead.
func (*UpdateStatusReply) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{7}
}

type ListNtReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NtList []*Notice `protobuf:"bytes,1,rep,name=ntList,proto3" json:"ntList,omitempty"`
	Num    int64     `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ListNtReply) Reset() {
	*x = ListNtReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNtReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNtReply) ProtoMessage() {}

func (x *ListNtReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNtReply.ProtoReflect.Descriptor instead.
func (*ListNtReply) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{8}
}

func (x *ListNtReply) GetNtList() []*Notice {
	if x != nil {
		return x.NtList
	}
	return nil
}

func (x *ListNtReply) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DeleteNtReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUuid string `protobuf:"bytes,2,opt,name=userUuid,proto3" json:"userUuid,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DeleteNtReq) Reset() {
	*x = DeleteNtReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNtReq) ProtoMessage() {}

func (x *DeleteNtReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNtReq.ProtoReflect.Descriptor instead.
func (*DeleteNtReq) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNtReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteNtReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *DeleteNtReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeleteNtReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNtReply) Reset() {
	*x = DeleteNtReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_v1_notify_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNtReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNtReply) ProtoMessage() {}

func (x *DeleteNtReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNtReply.ProtoReflect.Descriptor instead.
func (*DeleteNtReply) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{10}
}

var File_api_notify_v1_notify_proto protoreflect.FileDescriptor

var file_api_notify_v1_notify_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31, 0x2f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70,
	0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x73,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x2d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x52, 0x01, 0x6e, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x20, 0x0a, 0x02, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52,
	0x02, 0x6e, 0x74, 0x22, 0x7d, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x22, 0x51, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x49, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x06, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x4d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x87, 0x04, 0x0a, 0x05, 0x6e, 0x74, 0x53, 0x72, 0x76, 0x12,
	0x59, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x74, 0x12, 0x15, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x65, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x1a, 0x12, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x3a, 0x01,
	0x2a, 0x12, 0x78, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x74, 0x12, 0x13, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x42, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x3c, 0x12,
	0x3a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2f, 0x6c, 0x69, 0x73,
	0x74, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x7d, 0x2f, 0x7b, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x7d, 0x2f, 0x7b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x7d, 0x2f, 0x7b, 0x70,
	0x61, 0x67, 0x65, 0x7d, 0x2f, 0x7b, 0x74, 0x79, 0x70, 0x65, 0x7d, 0x12, 0x66, 0x0a, 0x08, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x74, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x2a,
	0x22, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x7d, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x5a, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x4e, 0x74, 0x12, 0x12, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x65, 0x74, 0x2f,
	0x7b, 0x69, 0x64, 0x7d, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x7d, 0x42,
	0x1f, 0x5a, 0x1d, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_notify_v1_notify_proto_rawDescOnce sync.Once
	file_api_notify_v1_notify_proto_rawDescData = file_api_notify_v1_notify_proto_rawDesc
)

func file_api_notify_v1_notify_proto_rawDescGZIP() []byte {
	file_api_notify_v1_notify_proto_rawDescOnce.Do(func() {
		file_api_notify_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_notify_v1_notify_proto_rawDescData)
	})
	return file_api_notify_v1_notify_proto_rawDescData
}

var file_api_notify_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_notify_v1_notify_proto_goTypes = []interface{}{
	(*Notice)(nil),            // 0: api.user.Notice
	(*CreateNtReq)(nil),       // 1: api.user.CreateNtReq
	(*CreateNtReply)(nil),     // 2: api.user.CreateNtReply
	(*GetNtReq)(nil),          // 3: api.user.GetNtReq
	(*GetNtReply)(nil),        // 4: api.user.GetNtReply
	(*ListNtReq)(nil),         // 5: api.user.ListNtReq
	(*UpdateStatusReq)(nil),   // 6: api.user.UpdateStatusReq
	(*UpdateStatusReply)(nil), // 7: api.user.UpdateStatusReply
	(*ListNtReply)(nil),       // 8: api.user.ListNtReply
	(*DeleteNtReq)(nil),       // 9: api.user.DeleteNtReq
	(*DeleteNtReply)(nil),     // 10: api.user.DeleteNtReply
}
var file_api_notify_v1_notify_proto_depIdxs = []int32{
	0,  // 0: api.user.CreateNtReq.n:type_name -> api.user.Notice
	0,  // 1: api.user.GetNtReply.nt:type_name -> api.user.Notice
	0,  // 2: api.user.ListNtReply.ntList:type_name -> api.user.Notice
	1,  // 3: api.user.ntSrv.CreateNt:input_type -> api.user.CreateNtReq
	6,  // 4: api.user.ntSrv.UpdateStatus:input_type -> api.user.UpdateStatusReq
	5,  // 5: api.user.ntSrv.ListNt:input_type -> api.user.ListNtReq
	9,  // 6: api.user.ntSrv.DeleteNt:input_type -> api.user.DeleteNtReq
	3,  // 7: api.user.ntSrv.GetNt:input_type -> api.user.GetNtReq
	2,  // 8: api.user.ntSrv.CreateNt:output_type -> api.user.CreateNtReply
	7,  // 9: api.user.ntSrv.UpdateStatus:output_type -> api.user.UpdateStatusReply
	8,  // 10: api.user.ntSrv.ListNt:output_type -> api.user.ListNtReply
	10, // 11: api.user.ntSrv.DeleteNt:output_type -> api.user.DeleteNtReply
	4,  // 12: api.user.ntSrv.GetNt:output_type -> api.user.GetNtReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_notify_v1_notify_proto_init() }
func file_api_notify_v1_notify_proto_init() {
	if File_api_notify_v1_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_notify_v1_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNtReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNtReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNtReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNtReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNtReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNtReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNtReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_v1_notify_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNtReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_notify_v1_notify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notify_v1_notify_proto_goTypes,
		DependencyIndexes: file_api_notify_v1_notify_proto_depIdxs,
		MessageInfos:      file_api_notify_v1_notify_proto_msgTypes,
	}.Build()
	File_api_notify_v1_notify_proto = out.File
	file_api_notify_v1_notify_proto_rawDesc = nil
	file_api_notify_v1_notify_proto_goTypes = nil
	file_api_notify_v1_notify_proto_depIdxs = nil
}
